[build]
  command = "npm install && npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  DATABASE_URL = ""
  JWT_SECRET = ""