[build]
  command = "npm ci --production=false && node scripts/build-production.js"
  publish = "dist/client"
  functions = "netlify/functions"
  included_files = ["netlify/functions/**/*.mjs"]

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api.mjs"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build configuration
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  DATABASE_URL = "postgresql://neondb_owner:npg_yACL0m5BGutI@ep-still-sound-aez4tryb.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require"
  JWT_SECRET = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
  SESSION_SECRET = "FcNpnO61ku19+vdeP9oxeclT1Yp9gFecmbcn+1s5ygSjsQ2zhZMkadFHf90rQkqjgbYkphWk2tM2WCnbIN9pQw=="
  ADMIN_EMAIL = "its.harshthakar@gmail.com"
  ADMIN_PASSWORD = "2004@Harsh"
  PGDATABASE = "neondb"
  PGHOST = "ep-still-sound-aez4tryb.c-2.us-east-2.aws.neon.tech"
  PGPORT = "5432"
  PGUSER = "neondb_owner"
  PGPASSWORD = "npg_yACL0m5BGutI"